---
# tasks file for roles/logstash
- name: Adding APT repository
  apt_repository:
   repo: deb  https://artifacts.elastic.co/packages/7.x/apt  stable main
   state: present

- name: Update repositories cache and install Logstash
  apt:
   name: logstash
   update_cache: yes

- name: Configure logstash.yml File
  copy:
    src: /path/to/your/logstash.yml
    dest: /etc/logstash/logstash.yml

- name: Configure  Filter
  template:
    src=filter.conf.j2
    dest=/etc/logstash/conf.d/filter.conf
    owner=root
    group=root
    mode=0644

- name: Configure input source
  template:
    src=input.conf.j2
    dest=/etc/logstash/conf.d/input.conf
    owner=root
    group=root
    mode=0644

- name: Configure output source
  template:
    src=output.conf.j2
    dest=/etc/logstash/conf.d/output.conf
    owner=root
    group=root
    mode=0644

- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes

- name: Start Logstash service
  systemd:
    name: logstash
    state: started
    daemon_reload: yes
